In [90]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [91]:
# Import data
data = pd.read_csv("../data/Churn_Modelling.csv")
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [92]:
# Drop unnecessary data
X = data.drop(["Exited","RowNumber","CustomerId","Surname"],axis=1)
y = data["Exited"]

In [93]:
# LabelEncoder
X["Gender"] = X["Gender"].map({"Female":0,"Male":1})

In [94]:
# OneHotEncoder data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_cols = ["Geography"]
transformer = ColumnTransformer(transformers=[("OneHot",OneHotEncoder(),categorical_cols)],remainder="passthrough")
X = transformer.fit_transform(X)

In [95]:
# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [96]:
# Standardize data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [97]:
# Building ANN
ann = tf.keras.models.Sequential() # Initializing the ANN model
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) # Adding the first layer
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) # Adding the second layer
ann.add(tf.keras.layers.Dense(units=1,activation="relu")) # Adding the output layer
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"]) # Compile the ANN model
ann.fit(X_train,y_train,batch_size=32,epochs=100) # Train the ANN model

Epoch 1/100
250/250 [==============================] - 1s 691us/step - loss: 3.4025 - accuracy: 0.5100
Epoch 2/100
250/250 [==============================] - 0s 615us/step - loss: 1.0423 - accuracy: 0.6990
Epoch 3/100
250/250 [==============================] - 0s 657us/step - loss: 0.7565 - accuracy: 0.7278
Epoch 4/100
250/250 [==============================] - 0s 736us/step - loss: 0.6577 - accuracy: 0.7525
Epoch 5/100
250/250 [==============================] - 0s 884us/step - loss: 0.5589 - accuracy: 0.7582
Epoch 6/100
250/250 [==============================] - 0s 759us/step - loss: 0.5017 - accuracy: 0.7770
Epoch 7/100
250/250 [==============================] - 0s 568us/step - loss: 0.4891 - accuracy: 0.7845
Epoch 8/100
250/250 [==============================] - 0s 552us/step - loss: 0.4802 - accuracy: 0.7886
Epoch 9/100
250/250 [==============================] - 0s 547us/step - loss: 0.4591 - accuracy: 0.7984
Epoch 10/100
250/250 [==============================] - 0s 576us/step - l

250/250 [==============================] - 0s 542us/step - loss: 0.3453 - accuracy: 0.8549
Epoch 80/100
250/250 [==============================] - 0s 506us/step - loss: 0.3383 - accuracy: 0.8632
Epoch 81/100
250/250 [==============================] - 0s 498us/step - loss: 0.3564 - accuracy: 0.8544
Epoch 82/100
250/250 [==============================] - 0s 508us/step - loss: 0.3350 - accuracy: 0.8661
Epoch 83/100
250/250 [==============================] - 0s 507us/step - loss: 0.3490 - accuracy: 0.8571
Epoch 84/100
250/250 [==============================] - 0s 545us/step - loss: 0.3520 - accuracy: 0.8547
Epoch 85/100
250/250 [==============================] - 0s 505us/step - loss: 0.3389 - accuracy: 0.8621
Epoch 86/100
250/250 [==============================] - 0s 511us/step - loss: 0.3443 - accuracy: 0.8593
Epoch 87/100
250/250 [==============================] - 0s 511us/step - loss: 0.3366 - accuracy: 0.8598
Epoch 88/100
250/250 [==============================] - 0s 516us/step - loss:

**Use our ANN model to predict if the customer with the following informations will leave the bank:**

Geography: France == 1,0,0

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [98]:
# Making prediction on trained ANN model
ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

array([[False]])

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

**Important note 3:** If you're dealing with non-binary classificatiom, loss = "categorical_crossentropy", activation = "softmax"

In [121]:
# Checking accuracy on trained ANN model
ann_preds = ann.predict(X_test)

In [122]:
y_test_show = np.array(y_test).reshape(-1,1)

In [123]:
ann_preds_show = np.array(ann_preds).reshape(-1,1)

In [130]:
ann_preds = ann.predict(X_test)> 0.5
show = np.concatenate((ann_preds.reshape(-1,1), np.array(y_test).reshape(-1,1)),1)

In [132]:
df = pd.DataFrame(show,columns=["Predicted","Real"])
df

Predicted  Real
0             0     0
1             0     1
2             0     0
3             0     0
4             0     0
...         ...   ...
1995          0     0
1996          0     0
1997          0     0
1998          0     0
1999          0     0

[2000 rows x 2 columns]

In [140]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,ann_preds)

array([[1565,   30],
       [ 268,  137]])

In [141]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,ann_preds)

0.851

In [142]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf_preds = rf.predict(X_test)
rf.score(X_test,y_test)

0.8685

In [143]:
from sklearn.metrics import confusion_matrix

confusion_matrix(rf_preds,ann_preds)

array([[1713,   11],
       [ 120,  156]])

In [144]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_train,y_train)
log_preds = rf.predict(X_test)
log.score(X_test,y_test)

0.811